(()=>{
"use strict";
const CORE=Array.isArray(window.NO_ALIBI_CORE_DECK)?window.NO_ALIBI_CORE_DECK:[];
if(CORE.length!==2000)throw new Error(`NO ALIBI deck did not initialize (${CORE.length}/2000)`);
const KEY="no-alibi-direct-v1";
const DEFAULTS={mode:"mixed",flavor:"full",mix:"full",unit:"SIP",maxPenalty:5,haptics:true};
const LEVELS={1:"WARM-UP",2:"NOSY",3:"MESSY",4:"BRUTAL",5:"NUCLEAR"};
const WEIGHTS={full:[20,25,25,20,10],light:[40,30,18,9,3],savage:[5,10,20,30,35]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={card:$("#promptCard"),copy:$("#promptCopy"),kind:$("#kindLabel"),tag:$("#tagLabel"),round:$("#roundLabel"),intensityName:$("#intensityName"),intensityNumber:$("#intensityNumber"),meter:$("#intensityMeter"),penalty:$("#penaltyNumber"),unit:$("#penaltyUnit"),drinkNum:$("#drinkButtonNumber"),drinkUnit:$("#drinkButtonUnit"),done:$("#doneButton"),drink:$("#drinkButton"),reshuffle:$("#forcePromptButton"),settings:$("#settingsButton"),history:$("#historyButton"),brand:$("#brandButton"),settingsDialog:$("#settingsDialog"),settingsForm:$("#settingsForm"),historyDialog:$("#historyDialog"),aboutDialog:$("#aboutDialog"),closeHistory:$("#closeHistoryButton"),closeHistoryFooter:$("#closeHistoryFooterButton"),closeAbout:$("#closeAboutButton"),clearHistory:$("#clearHistoryButton"),historyList:$("#historyList"),historyEmpty:$("#historyEmpty"),roundCount:$("#roundCount"),doneCount:$("#completedCount"),passedCount:$("#passedCount"),builtInCount:$("#builtInCount"),customCount:$("#customCount"),seenCount:$("#seenCount"),flavorInput:$("#flavorInput"),mixInput:$("#mixInput"),unitInput:$("#penaltyUnitInput"),maxInput:$("#maxPenaltyInput"),hapticsInput:$("#hapticsInput"),importBtn:$("#importPackButton"),exportBtn:$("#exportPackButton"),templateBtn:$("#templatePackButton"),resetSeen:$("#resetSeenButton"),clearCustom:$("#clearCustomButton"),file:$("#packFileInput"),packStatus:$("#packStatus"),toast:$("#toast"),modes:$$('.mode-switch button[data-mode]')};
let saved=readStore();
let state={settings:{...DEFAULTS,...saved.settings},seen:new Set(Array.isArray(saved.seen)?saved.seen:[]),custom:Array.isArray(saved.custom)?saved.custom.map(normalizeCard).filter(Boolean):[],history:[],done:0,passed:0,current:null,round:0,busy:false,toastTimer:0};
init();
function init(){bind();syncMode();syncSettingsForm();updateStats();draw(false);if("serviceWorker"in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register("./sw.js?v=1",{updateViaCache:"none"}).catch(()=>{});}
function bind(){el.modes.forEach(b=>b.addEventListener("click",()=>{state.settings.mode=b.dataset.mode;syncMode();persist();draw(true)}));el.done.addEventListener("click",()=>advance("done"));el.drink.addEventListener("click",()=>advance("passed"));el.reshuffle.addEventListener("click",()=>draw(true));el.settings.addEventListener("click",openSettings);el.history.addEventListener("click",()=>{renderHistory();openDialog(el.historyDialog)});el.brand.addEventListener("click",()=>openDialog(el.aboutDialog));el.closeHistory.addEventListener("click",()=>closeDialog(el.historyDialog));el.closeHistoryFooter.addEventListener("click",()=>closeDialog(el.historyDialog));el.closeAbout.addEventListener("click",()=>closeDialog(el.aboutDialog));el.clearHistory.addEventListener("click",()=>{state.history=[];state.done=0;state.passed=0;updateStats();renderHistory();toast("Session cleared")});el.settingsForm.addEventListener("submit",saveSettings);el.importBtn.addEventListener("click",()=>el.file.click());el.file.addEventListener("change",importPack);el.exportBtn.addEventListener("click",exportPack);el.templateBtn.addEventListener("click",downloadTemplate);el.resetSeen.addEventListener("click",()=>{state.seen.clear();persist();updateStats();toast("Shuffle memory reset")});el.clearCustom.addEventListener("click",()=>{state.custom=[];persist();updateStats();toast("Imported cards removed")});[el.settingsDialog,el.historyDialog,el.aboutDialog].forEach(d=>d.addEventListener("click",e=>{if(e.target===d)closeDialog(d)}));document.addEventListener("keydown",e=>{if(e.key==="ArrowRight"||e.key===" "){e.preventDefault();draw(true)}if(e.key.toLowerCase()==="t"){state.settings.mode="truth";syncMode();draw(true)}if(e.key.toLowerCase()==="d"){state.settings.mode="dare";syncMode();draw(true)}if(e.key.toLowerCase()==="m"){state.settings.mode="mixed";syncMode();draw(true)}})}
function draw(animated=true){if(state.busy)return;state.busy=true;const reveal=()=>{const type=state.settings.mode==="mixed"?(rand()<.5?"truth":"dare"):state.settings.mode;const level=rollLevel(state.settings.mix);let pool=allCards().filter(c=>c.type===type&&c.intensity===level&&flavorMatch(c));if(!pool.length)pool=allCards().filter(c=>c.type===type&&c.intensity===level);if(!pool.length)pool=allCards().filter(c=>c.type===type);let available=pool.filter(c=>!state.seen.has(c.id));if(!available.length){pool.forEach(c=>state.seen.delete(c.id));available=pool}const card=available[Math.floor(rand()*available.length)]||CORE[0];state.seen.add(card.id);state.current=card;state.round++;renderCard(card);persist();updateStats();haptic(card.intensity);state.busy=false};if(animated){el.card.classList.add("out");setTimeout(()=>{reveal();requestAnimationFrame(()=>el.card.classList.remove("out"))},190)}else reveal()}
function renderCard(c){const penalty=Math.max(1,Math.min(Number(state.settings.maxPenalty)||5,Number(c.penalty)||c.intensity));const unit=unitLabel(penalty);el.card.className=`prompt-card ${c.type}`;el.copy.textContent=c.text;el.kind.textContent=c.type.toUpperCase();el.tag.textContent=c.tag||c.category||"CHAOS";el.round.textContent=`ROUND ${String(state.round).padStart(2,"0")}`;el.intensityName.textContent=LEVELS[c.intensity]||"CHAOS";el.intensityNumber.textContent=`${c.intensity} / 5`;el.meter.setAttribute("aria-label",`Intensity ${c.intensity} out of 5`);[...el.meter.children].forEach((x,i)=>x.classList.toggle("on",i<c.intensity));el.penalty.textContent=penalty;el.unit.textContent=unit;el.drinkNum.textContent=penalty;el.drinkUnit.textContent=unit}
function advance(result){if(!state.current||state.busy)return;state.history.unshift({result,at:Date.now(),card:{...state.current}});state.history=state.history.slice(0,80);if(result==="done")state.done++;else state.passed++;updateStats();draw(true)}
function allCards(){return CORE.concat(state.custom)}
function flavorMatch(c){const f=state.settings.flavor;return f==="full"||Array.isArray(c.flavors)&&c.flavors.includes(f)}
function rollLevel(mix){const w=WEIGHTS[mix]||WEIGHTS.full;let r=rand()*w.reduce((a,b)=>a+b,0);for(let i=0;i<w.length;i++){r-=w[i];if(r<0)return i+1}return 3}
function rand(){if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}return Math.random()}
function syncMode(){el.modes.forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.mode===state.settings.mode)))}
function updateStats(){el.roundCount.textContent=state.history.length;el.doneCount.textContent=state.done;el.passedCount.textContent=state.passed;el.builtInCount.textContent=CORE.length.toLocaleString();el.customCount.textContent=state.custom.length.toLocaleString();el.seenCount.textContent=state.seen.size.toLocaleString()}
function openSettings(){syncSettingsForm();el.packStatus.textContent="";openDialog(el.settingsDialog)}
function syncSettingsForm(){el.flavorInput.value=state.settings.flavor;el.mixInput.value=state.settings.mix;el.unitInput.value=state.settings.unit;el.maxInput.value=String(state.settings.maxPenalty);el.hapticsInput.checked=!!state.settings.haptics}
function saveSettings(e){e.preventDefault();if(e.submitter?.value==="cancel"){closeDialog(el.settingsDialog);return}state.settings.flavor=el.flavorInput.value;state.settings.mix=el.mixInput.value;state.settings.unit=safeUnit(el.unitInput.value);state.settings.maxPenalty=Number(el.maxInput.value)||5;state.settings.haptics=el.hapticsInput.checked;persist();closeDialog(el.settingsDialog);draw(true)}
function renderHistory(){el.historyList.innerHTML="";el.historyEmpty.hidden=state.history.length>0;state.history.forEach(h=>{const li=document.createElement("li"),title=document.createElement("strong"),p=document.createElement("p");title.textContent=`${h.result==="done"?"DONE":"PASSED"} · ${h.card.type.toUpperCase()} · ${h.card.intensity}/5`;p.textContent=h.card.text;li.append(title,p);el.historyList.append(li)})}
function normalizeCard(c,i=0){if(!c||typeof c!=="object")return null;const type=c.type==="dare"?"dare":c.type==="truth"?"truth":null,text=String(c.text||c.prompt||"").trim(),intensity=Math.max(1,Math.min(5,Number(c.intensity)||3));if(!type||text.length<8)return null;return{id:String(c.id||`import-${hash(text)}-${i}`),type,intensity,penalty:Math.max(1,Math.min(5,Number(c.penalty)||intensity)),tag:String(c.tag||"IMPORTED").slice(0,24).toUpperCase(),category:String(c.category||"custom"),flavors:Array.isArray(c.flavors)?c.flavors.filter(x=>["filthy","ruthless","absurd","exposed"].includes(x)):[],text:text.slice(0,500),pack:String(c.pack||"imported")}}
async function importPack(){const file=el.file.files?.[0];el.file.value="";if(!file)return;try{const parsed=JSON.parse(await file.text()),cards=Array.isArray(parsed)?parsed:parsed.cards;if(!Array.isArray(cards))throw new Error("No cards array found");const existing=new Set(allCards().map(c=>c.id)),added=[];cards.forEach((c,i)=>{const n=normalizeCard(c,i);if(n&&!existing.has(n.id)){existing.add(n.id);added.push(n)}});if(!added.length)throw new Error("No valid new cards found");state.custom.push(...added);persist();updateStats();el.packStatus.textContent=`Imported ${added.length} card${added.length===1?"":"s"}.`;toast(`${added.length} cards imported`)}catch(err){el.packStatus.textContent=String(err.message||err);toast("Import failed")}}
function exportPack(){if(!state.custom.length){toast("No imported cards to export");return}downloadJSON({schema:"no-alibi-card-pack/v1",name:"NO ALIBI Imported Cards",version:1,cards:state.custom},"no-alibi-imported-pack.json")}
function downloadTemplate(){downloadJSON({schema:"no-alibi-card-pack/v1",name:"My Expansion Pack",version:1,cards:[{id:"custom-truth-001",type:"truth",intensity:5,penalty:5,tag:"CUSTOM",category:"custom",flavors:["ruthless","exposed"],text:"Your new question goes here."},{id:"custom-dare-001",type:"dare",intensity:4,penalty:4,tag:"CUSTOM",category:"custom",flavors:["absurd"],text:"Your new dare goes here."}]},"no-alibi-pack-template.json")}
function downloadJSON(data,name){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function unitLabel(n){const u=safeUnit(state.settings.unit);return n===1?u:u.endsWith("S")?u:`${u}S`}
function safeUnit(v){return String(v||"SIP").replace(/[^a-z0-9 -]/gi,"").trim().slice(0,12).toUpperCase()||"SIP"}
function persist(){writeStore({settings:state.settings,seen:[...state.seen].slice(-5000),custom:state.custom})}
function readStore(){try{return JSON.parse(localStorage.getItem(KEY)||"{}")||{}}catch{return{}}}
function writeStore(v){try{localStorage.setItem(KEY,JSON.stringify(v))}catch{}}
function hash(s){let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function openDialog(d){if(typeof d.showModal==="function")d.showModal();else d.setAttribute("open","")}
function closeDialog(d){if(typeof d.close==="function")d.close();else d.removeAttribute("open")}
function haptic(level){if(state.settings.haptics&&navigator.vibrate)navigator.vibrate(level===5?[18,30,24]:8+level*3)}
function toast(msg){clearTimeout(state.toastTimer);el.toast.textContent=msg;el.toast.classList.add("show");state.toastTimer=setTimeout(()=>el.toast.classList.remove("show"),2400)}
})();
