(()=>{
const D=[];
const P={1:[1,1,1,1,2],2:[1,2,2,2,3],3:[2,3,3,3,4],4:[3,4,4,4,5],5:[4,5,5,5,5]};
const clean=s=>{s=String(s).replace(/\s+/g," ").trim().replace(" ?","?").replace(" .",".");return s&&!/[.?!]$/.test(s)?s+".":s};
function F(type,level,tag,category,flavors,template,a,b){if(a.length!==10||b.length!==5)throw new Error("Bad deck family");let base=D.filter(c=>c.type===type&&c.intensity===level).length;for(let i=0;i<10;i++)for(let j=0;j<5;j++){const n=base+i*5+j+1;D.push({id:`core-${type}-${level}-${String(n).padStart(3,"0")}`,type,intensity:level,penalty:P[level][(i+j+base/50)%5],tag,category,flavors,text:clean(template.replace("{a}",a[i]).replace("{b}",b[j])),pack:"core-2000"})}}

F("truth",1,"PETTY","confession",["ruthless","exposed"],"What is the {a} {b}?",["pettiest","most childish","most dramatic","most hypocritical","most unnecessary","cheapest","laziest","most shameless","most ridiculous","most embarrassing"],["lie you told this week","reason you stopped replying","excuse you used to cancel","thing you judged someone for","move you pulled to get your way"]);
F("truth",1,"ROOM READ","group",["ruthless","exposed"],"Who here is most likely to {a}? Give {b}.",["forget your birthday","spill a secret by accident","start drama and deny it","become famous for something stupid","win an argument they started wrong","date the worst possible person","fake being busy to avoid plans","turn a tiny problem into a crisis","get banned from a group chat","survive longest on a trashy reality show"],["the exact reason","one piece of evidence","a recent example","your brutally honest logic","the first name that came to mind and why"]);
F("truth",1,"PHONE CRUMBS","phone",["exposed","absurd"],"What is the {a} {b}?",["last search","most-used emoji","oldest selfie","strangest note title","most embarrassing app","last screenshot","weirdest contact nickname","most chaotic saved meme","most suspicious recent tab","ugliest photo you refuse to delete"],["you can explain in one sentence","you hope nobody asks about","that says too much about you","that would confuse your parents","that belongs in a courtroom exhibit"]);
F("truth",1,"ICK","dating",["filthy","absurd"],"{a} {b}?",["What gives you an instant ick","What is your shallowest deal-breaker","Which green flag do you distrust","Which bad pickup line might work on you","What kind of person do you keep falling for","Which weird deal-breaker do you defend","Which red flag do you romanticize","Which compliment works on you","Which bad habit do you forgive","Which physical type do you deny liking"],["on a first date","in someone's profile","while texting","at a party","once things get serious"]);

F("truth",2,"GHOSTED","dating",["filthy","exposed"],"Admit the most recent time you {a} {b}.",["ghosted someone","kept someone on read","sent a bait text","gave a fake excuse","replied only for attention","cancelled a date","lied about being busy","soft-launched jealousy","stalked an ex","pretended not to remember someone"],["because you were bored","because someone better appeared","because you felt embarrassed","because you wanted control","because you knew it would start drama"]);
F("truth",2,"JEALOUS","envy",["ruthless","exposed"],"What about the {b} of {a} makes you jealous or judgmental?",["someone in this room","your closest friend","an ex","a coworker or classmate","a person you follow online","your sibling","your current or last partner","the person on your left","the person on your right","someone you claim not to care about"],["looks","money","confidence","dating life","social life"]);
F("truth",2,"EX FILES","dating",["filthy","exposed"],"Which {a} do you {b}, and why?",["former partner","old crush","past situationship","one-night stand","person from your dating past","person who rejected you","person you rejected","friend you once wanted","online flirt","person you nearly dated"],["still reply to tonight","still check up on","want to revisit if single","compare new people to","hate seeing thrive"]);
F("truth",2,"TURN-ON","sex",["filthy"],"What {a} {b}?",["personality trait","body feature","voice or accent","outfit","bad idea","power dynamic","compliment","kind of confidence","toxic behavior","unexpected physical detail"],["turns you on instantly","has made you ignore a red flag","you pretend not to care about","works on you every time","would make you fold tonight"]);

F("truth",3,"HORNY TRUTH","sex",["filthy","exposed"],"What is the most {a} {b} you can admit without naming anyone?",["shameless","embarrassing","ego-destroying","unexpected","questionable","desperate","funniest","reckless","out-of-character","feral"],["hookup decision","fantasy you acted on","sext you sent","turn-on you discovered","post-sex thought"]);
F("truth",3,"CHEMISTRY","group",["filthy","ruthless"],"Who here would you most want to {a} {b}, and why?",["kiss","hook up with","date for six months","wake up next to","trust to see you naked","take on a secret weekend away","send a risky text to","make out with","share a bed with","have undeniable tension with"],["if everyone were single","if there were zero fallout","based only on chemistry","after one more round","if nobody could ever mention it"]);
F("truth",3,"BOUNDARY","relationships",["filthy","ruthless","exposed"],"Have you ever {a} {b}? Tell the full story.",["flirted with someone else","secretly messaged an ex","deleted messages","lied about where you were","kept a backup option","made someone jealous on purpose","withheld affection","used guilt to control a decision","kept someone interested for attention","pretended not to care to gain power"],["while committed","to make someone jealous","then lied when asked","and convinced yourself it was harmless","because you wanted a backup option"]);
F("truth",3,"BURIED","secrets",["ruthless","exposed"],"What is the {a} {b}?",["secret","regret","lie","set of screenshots","deleted message","body insecurity","sexual insecurity","friendship betrayal","money lie","apology you avoided"],["you would hate to explain","you have never admitted aloud","you still think about at 2 a.m.","that would change how this room sees you","you wish you could erase"]);

F("truth",4,"BIG LIE","secrets",["ruthless","exposed"],"What is the {a} {b}?",["relationship","friendship","money","sex-life","past","career","family","dating-history","social-media","personal-image"],["lie you are still maintaining","truth you deliberately edited","detail you deleted from the story","secret someone trusted you to keep","fact that would change how people see you"]);
F("truth",4,"BETRAYAL","betrayal",["ruthless","exposed"],"Which {a} did you {b}, and what happened?",["partner","best friend","family member","coworker or classmate","person who trusted you","ex","close friend","roommate","mentor","person who defended you"],["betray for convenience","use for access","lie to repeatedly","abandon when they needed you","blame for your own mistake"]);
F("truth",4,"RESENTMENT","group",["ruthless"],"Who is the {a} you {b}, and what is the ugly truth?",["friend","partner","ex","relative","person in this room","coworker or classmate","roommate","former friend","person you claim to support","person you keep close"],["secretly resent","would cut off first","trust least","think has settled for less in life","believe does not deserve their success"]);
F("truth",4,"SEX SECRET","sex",["filthy","exposed"],"What is the {a} {b}?",["hookup","fantasy","boundary crossing","sexting situation","hookup overlap","sexual lie","secret attraction","relationship exit plan","unresolved ex situation","adult secret"],["that a partner never learned about","that you would deny under pressure","that still affects a friendship","that made you feel guilty","that could start a fight tonight"]);

F("truth",5,"NUCLEAR","secrets",["ruthless","exposed"],"What is the {a} {b}?",["relationship","friendship","family","sex-life","money","career","reputation","dating-history","private-message","identity"],["secret that would cause the most damage","lie with the biggest fallout","truth you are most desperate to contain","fact that could permanently change someone's opinion","thing you deleted evidence of"]);
F("truth",5,"USED","manipulation",["ruthless","exposed"],"Who was the {a} you kept around {b}, and what did you get from them?",["person","friend","partner","hookup","ex","coworker","roommate","admirer","backup option","loyal supporter"],["for attention","for money or access","to avoid being alone","to make someone else jealous","because they were useful"]);
F("truth",5,"TABOO","sex",["filthy","ruthless","exposed"],"Think of {a}. {b}, and what makes it taboo?",["a friend's partner","an ex's friend","a boss or authority figure","someone you should hate","someone in this room","a partner's friend","a close friend's ex","someone everyone warned you about","someone completely outside your usual type","someone whose name would shock the room"],["Have you fantasized about them","Would you sleep with them if consequences vanished","Do you secretly compare other people to them","Have you flirted with them in your head","Would you choose them over your usual type"]);
F("truth",5,"ROOM DAMAGE","group",["ruthless","exposed"],"Name the person here you would {a}; {b}.",["cut off first","betray under pressure","trust least around your partner","refuse to lend serious money to","say is secretly against you","sleep with if everyone were single","never defend in an argument","least want as a roommate","call the fakest","choose last in a crisis"],["give the exact reason","cite one piece of evidence","do not soften it","say what you think they say about you","let them ask one follow-up"]);

F("dare",1,"NARRATOR","performance",["absurd"],"Give a 20-second {a} narration of {b}.",["furious sports-commentator","overconfident life-coach","tragic Shakespeare-actor","nature-documentary","cheap reality-show villain","true-crime narrator","late-night infomercial host","celebrity gossip reporter","romance-audiobook narrator","conspiracy podcaster"],["someone taking a sip","the person on your left checking their phone","you walking across the room","the nearest snack","the group deciding who goes next"]);
F("dare",1,"SCENE PARTNER","performance",["absurd"],"Use {a} as your scene partner and {b}.",["a chair","a cup","a pillow","your phone","a jacket","a snack","the nearest lamp","an empty seat","your own reflection","the least attractive object nearby"],["perform a 20-second breakup speech","propose marriage dramatically","rehearse a terrible first date","deliver an Oscar-worthy apology","act out a jealous confrontation"]);
F("dare",1,"IMPRESSION","group",["absurd","ruthless"],"Do your best impression of {a} while {b}.",["the person on your left","the person on your right","the loudest player","the quietest player","the host","someone who arrived late","the best-dressed player","the person who laughs the most","the person most likely to argue","yourself when you are drunk"],["ordering fast food","getting rejected","trying to sound intelligent","telling an obvious lie","flirting badly"]);
F("dare",1,"CONFIDENCE","performance",["absurd","filthy"],"For 20 seconds, {a} like {b}.",["walk across the room","introduce yourself","compliment yourself","pitch yourself as a date","announce your next move","pose for an imaginary camera","give an acceptance speech","ask for someone's number","sell the nearest object","explain your dating type"],["you are painfully famous","you know everyone wants you","you are a supervillain","you are on a trashy dating show","you have never felt embarrassment"]);

F("dare",2,"PHONE RECEIPTS","phone",["exposed"],"Show your {a} and {b}.",["last five emojis","recently-deleted photo count","three most-used apps","last screenshot","strangest contact nickname","screen-time report","last saved post","oldest open tab","recent search list","last five camera-roll thumbnails"],["explain each without lying","let the room ask one follow-up","defend the worst one","turn it into a confession","say what it exposes about you"]);
F("dare",2,"COMMIT","performance",["absurd","filthy"],"Perform the {a} version of {b} for 30 seconds.",["sexiest","most dramatic","most off-key","most aggressive","most heartbroken","most seductive","most desperate","most arrogant","most emotional","most chaotic"],["a chorus the group chooses","a commercial jingle","the birthday song","a nursery rhyme","the song currently stuck in your head"]);
F("dare",2,"FIRST READ","group",["ruthless","exposed"],"Pick the {a} and {b}.",["person on your left","person on your right","person opposite you","quietest player","loudest player","person you know best","person you know least","best-dressed player","most intimidating player","person who arrived last"],["give your honest first impression","name their funniest red flag","say what role they would play in a heist","guess their dating-app bio","describe what kind of ex they would be"]);
F("dare",2,"FLIRT","flirty",["filthy","absurd"],"Choose {a} as your scene partner and {b}.",["a chair","a snack","your own reflection","a consenting player","the room's ugliest object","a pillow","a jacket","an empty seat","your phone","the nearest drink"],["deliver your best pickup line","perform a 20-second thirst-trap monologue","make a dramatic date proposal","act possessively jealous","stage an over-the-top breakup"]);

F("dare",3,"CHEMISTRY","group",["filthy","exposed"],"Choose the {a} and {b}.",["person here you find most attractive","person here with the best voice","person here you would trust on a date","person here who gives dangerous chemistry","person here most unlike your usual type","person here with the best smile","person here you would flirt with first","person here you find most intimidating","person here you would take on a weekend away","person here most likely to break your heart"],["tell them exactly why","give them a 30-second sincere compliment","describe your hypothetical first move","name the feature that got your attention","say what would make you fold"]);
F("dare",3,"PHONE OPEN","phone",["filthy","exposed"],"Open your phone to the {a}; {b}.",["last profile you searched","last message you sent to a crush","last photo you took to look hot","most suspicious note title","last screenshot involving dating","oldest thirst trap","last outgoing flirt","most embarrassing draft","most chaotic selfie","last saved dating meme"],["show it with names hidden","explain the context honestly","let the room ask two questions","read only your own words","say what you hoped would happen"]);
F("dare",3,"ADULT THEATER","performance",["filthy","absurd"],"Use the {b} as your scene partner for a 30-second {a}.",["lap dance","dirty-talk monologue","fake-orgasm scene","seductive commercial","fully-clothed strip-club audition","morning-after speech","hookup negotiation","jealous-lover scene","thirst-trap audition","dramatic rejection"],["chair","pillow","lamp","jacket","empty side of the couch"]);
F("dare",3,"SELF ROAST","confession",["ruthless","exposed","absurd"],"Give a 45-second {b} about your {a}.",["dating history","sexual confidence","worst red flag","most desperate moment","last breakup","taste in partners","biggest ick","most toxic habit","worst flirt","relationship résumé"],["stand-up set","courtroom confession","TED Talk","product recall","apology press conference"]);

F("dare",4,"FACE THEM","group",["ruthless","filthy","exposed"],"Choose the {a}; {b}.",["person here you trust least","person here you are most attracted to","person here you would never date","person here you think hides the most","person here you owe honesty","person here you envy","person here you misunderstood","person here you would call at 3 a.m.","person here you think has settled for less","person here you have the weirdest tension with"],["tell them the exact reason","name the moment that decided it","give one compliment and one brutal truth","say what you would change about the dynamic","answer their one follow-up honestly"]);
F("dare",4,"OUTGOING","phone",["filthy","exposed"],"Find your {a} and {b}.",["last flirty message you sent","most embarrassing outgoing DM","own line from a sext","message you typed and deleted","last apology you sent","most desperate text","riskiest compliment","last message to an ex","worst pickup line","most revealing unsent draft"],["read it with names removed","paraphrase it dramatically","explain what you wanted back","let the room rate it","say whether you still stand by it"]);
F("dare",4,"AFTER DARK","performance",["filthy","absurd"],"Perform a 45-second {a} {b}.",["over-clothes lap dance","seduction scene","fake-hookup negotiation","dirty-talk audition","morning-after monologue","fully-clothed striptease","jealous-partner scene","desperate thirst-trap pitch","dominant flirt scene","one-night-stand review"],["with a chair","with a pillow","to your reflection","to an empty spot chosen by the room","with a consenting volunteer who can opt out"]);
F("dare",4,"VOLUNTEER","flirty",["filthy","exposed"],"Choose {a} and {b}.",["a consenting adult player","a volunteer","the consenting person you have most chemistry with","a consenting person you would not normally flirt with","the room's choice among volunteers","a consenting person you know least","a consenting person you know best","a consenting person outside your usual type","a consenting person who intimidates you","any willing adult player"],["give them a 30-second sincere seduction pitch","trade your biggest turn-ons","hold hands and maintain eye contact for one minute","ask each other one explicit but respectful question","act out a painfully awkward first kiss without touching"]);

F("dare",5,"NO ALIBI","group",["filthy","ruthless","exposed"],"Choose the {a} and {b}.",["person here you have the most unresolved tension with","person here you secretly judge hardest","person here you would choose for one consequence-free night","person here you trust least","person here you have used emotionally","person here you envy most","person here you think is fake","person here you would cut off first","person here you are most sexually curious about","person here you owe the ugliest truth"],["tell them the full truth for one minute","say the sentence you have been avoiding","name the exact moment it started","admit what you wanted from them","answer their one follow-up with no joke"]);
F("dare",5,"FERAL THEATER","performance",["filthy","absurd"],"Perform a 60-second {a} {b}.",["fully-clothed striptease","graphic dirty-talk monologue","fake-orgasm acting challenge","dominant seduction scene","desperate hookup pitch","jealous-lover breakdown","morning-after confession","thirst-trap audition","one-night-stand negotiation","seductive villain monologue"],["to a chair","to your reflection","with a pillow as scene partner","to a consenting volunteer who can stop it anytime","to the room without touching anyone"]);
F("dare",5,"EVIDENCE","phone",["filthy","exposed"],"Find your {a} and {b}.",["most incriminating dating search","own sent sext line","hidden photo-album title","deleted-message screenshot","most embarrassing saved thirst trap","riskiest outgoing DM","most suspicious note title","last profile you stalked","worst dating-app opener","most revealing draft"],["show or read it with identities hidden","explain the uncensored context","let the room ask three questions","admit why it exists","say what it reveals about you"]);
F("dare",5,"ASK ANYTHING","confession",["filthy","ruthless","exposed"],"Let the room challenge your {a}: {b}.",["sex life","kink","body count","worst hookup","most shameful fantasy","biggest lie to a partner","most manipulative dating move","cruelest act toward a friend","most selfish sexual decision","worst post-breakup act"],["answer one majority-vote question honestly","take one follow-up from the person on your left","answer a yes-or-no question from each player","answer the question everyone thinks you will dodge","give a courtroom-style confession with no minimizing"]);

if(D.length!==2000)throw new Error(`Deck count ${D.length}`);
window.NO_ALIBI_CORE_DECK=D;
})();
